// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ1SCUYhUXn_lueiSaS81B2lTcWpVjr9M',
    appId: '1:512914854505:web:0b2c4969f1ebf9fcca48f8',
    messagingSenderId: '512914854505',
    projectId: 'ekub-1fecf',
    authDomain: 'ekub-1fecf.firebaseapp.com',
    storageBucket: 'ekub-1fecf.firebasestorage.app',
    measurementId: 'G-E1X7P99GG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT7H-dfhrlcDstz4c2OSIpVVcP7iTBcqw',
    appId: '1:512914854505:android:ce5155175d4c5f7dca48f8',
    messagingSenderId: '512914854505',
    projectId: 'ekub-1fecf',
    storageBucket: 'ekub-1fecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhPbCmLRUY5YaEn7MrQ5VhN7oqnMRvChc',
    appId: '1:512914854505:ios:63d671f17785ce3cca48f8',
    messagingSenderId: '512914854505',
    projectId: 'ekub-1fecf',
    storageBucket: 'ekub-1fecf.firebasestorage.app',
    iosBundleId: 'com.example.ekub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhPbCmLRUY5YaEn7MrQ5VhN7oqnMRvChc',
    appId: '1:512914854505:ios:63d671f17785ce3cca48f8',
    messagingSenderId: '512914854505',
    projectId: 'ekub-1fecf',
    storageBucket: 'ekub-1fecf.firebasestorage.app',
    iosBundleId: 'com.example.ekub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ1SCUYhUXn_lueiSaS81B2lTcWpVjr9M',
    appId: '1:512914854505:web:4d600177986b8805ca48f8',
    messagingSenderId: '512914854505',
    projectId: 'ekub-1fecf',
    authDomain: 'ekub-1fecf.firebaseapp.com',
    storageBucket: 'ekub-1fecf.firebasestorage.app',
    measurementId: 'G-PVY43N8MJX',
  );
}
